services:
  app:
    build: .
    container_name: fintar-app
    ports:
      - "8080:8080"
    depends_on:
      - mssql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=${SPRING_DATASOURCE_DB};encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}
    networks:
      - fintar-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-2022
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - fintar-network

  redis:
    image: redis:7.2
    container_name: redis
    environment:
      REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${SPRING_DATA_REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - fintar-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks:
      - fintar-network

volumes:
  mssql-data:
  redis-data:


networks:
  fintar-network:
